# Generated by Django 4.2.13 on 2026-08-09 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RbacUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognito_sub', models.CharField(max_length=64, unique=True)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_sub', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rbac_user',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('unit_1', 'Unit 1'), ('unit_2', 'Unit 2'), ('unit_11', 'Unit 11')], max_length=32)),
                ('can_goods_in', models.BooleanField(default=False)),
                ('can_goods_out', models.BooleanField(default=False)),
                ('goods_in_previous', models.BooleanField(default=False)),
                ('goods_in_today', models.BooleanField(default=False)),
                ('goods_in_future', models.BooleanField(default=False)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_access', to='users_rbac.rbacuser')),
            ],
            options={
                'db_table': 'rbac_warehouse_access',
            },
        ),
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('production', 'Production'), ('warehouse', 'Warehouse'), ('admin', 'Admin')], max_length=32)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='users_rbac.rbacuser')),
            ],
            options={
                'db_table': 'rbac_user_department',
            },
        ),
        migrations.CreateModel(
            name='RbacAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('user.created', 'User created'), ('user.updated', 'User updated'), ('user.enabled', 'User enabled'), ('user.disabled', 'User disabled'), ('user.password_reset', 'User password reset'), ('grants.replaced', 'Grants replaced'), ('auth.login_success', 'Login success'), ('auth.login_failure', 'Login failure'), ('auth.access_denied', 'Access denied')], max_length=64)),
                ('actor_sub', models.CharField(blank=True, max_length=64, null=True)),
                ('actor_username', models.CharField(blank=True, max_length=128, null=True)),
                ('actor_display_name', models.CharField(blank=True, max_length=128, null=True)),
                ('target_username', models.CharField(blank=True, max_length=128, null=True)),
                ('target_sub', models.CharField(blank=True, max_length=64, null=True)),
                ('request_method', models.CharField(blank=True, max_length=8, null=True)),
                ('request_path', models.CharField(blank=True, max_length=512, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('source_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('detail_json', models.JSONField(blank=True, null=True)),
                ('target_user', models.ForeignKey(blank=True, db_column='target_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events_as_target', to='users_rbac.rbacuser')),
            ],
            options={
                'db_table': 'rbac_audit_event',
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('low_risk', 'Low Risk'), ('high_risk', 'High Risk'), ('sleeving', 'Sleeving'), ('dispatch', 'Dispatch')], max_length=32)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='production_access', to='users_rbac.rbacuser')),
            ],
            options={
                'db_table': 'rbac_production_access',
            },
        ),
        migrations.CreateModel(
            name='AdminAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('technical', 'Technical'), ('operational', 'Operational'), ('npd', 'NPD'), ('finance', 'Finance')], max_length=32)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='admin_access', to='users_rbac.rbacuser')),
            ],
            options={
                'db_table': 'rbac_admin_access',
            },
        ),
        migrations.AddConstraint(
            model_name='warehouseaccess',
            constraint=models.UniqueConstraint(fields=('user', 'unit'), name='uq_rbac_warehouse_access'),
        ),
        migrations.AddConstraint(
            model_name='userdepartment',
            constraint=models.UniqueConstraint(fields=('user', 'department'), name='uq_rbac_user_department'),
        ),
        migrations.AddIndex(
            model_name='rbacauditevent',
            index=models.Index(fields=['actor_sub', '-at'], name='idx_rbac_audit_actor_at'),
        ),
        migrations.AddIndex(
            model_name='rbacauditevent',
            index=models.Index(fields=['target_user', '-at'], name='idx_rbac_audit_target_at'),
        ),
        migrations.AddConstraint(
            model_name='productionaccess',
            constraint=models.UniqueConstraint(fields=('user', 'area'), name='uq_rbac_production_access'),
        ),
        migrations.AddConstraint(
            model_name='adminaccess',
            constraint=models.UniqueConstraint(fields=('user', 'area'), name='uq_rbac_admin_access'),
        ),
    ]
