# Generated by Django 4.2.30 on 2026-07-28 12:08

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_productacceptance_productingredientlabel_and_more'),
        ('locations', '0002_loc_edge_relation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recipe', to='product.product')),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
        migrations.CreateModel(
            name='RecipeVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('process_loss', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10)),
                ('batch_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('sum_batch_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('sum_net_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('sum_gross_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_version_batches', to='product.unit')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_versions', to='locations.location')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='recipe.recipe')),
            ],
            options={
                'db_table': 'recipe_version',
            },
        ),
        migrations.CreateModel(
            name='RecipeComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('line_no', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=16)),
                ('batch_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('gross_batch_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('step_instructions', models.TextField(blank=True, null=True)),
                ('is_implicit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipe_components', to='product.product')),
                ('recipe_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='recipe.recipeversion')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_components', to='product.unit')),
            ],
            options={
                'db_table': 'recipe_component',
            },
        ),
        migrations.AddIndex(
            model_name='recipeversion',
            index=models.Index(fields=['recipe', 'status'], name='idx_recipe_version_status'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.UniqueConstraint(fields=('recipe', 'version_number'), name='uq_recipe_version_number'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['draft', 'approved', 'active', 'retired'])), name='chk_recipe_version_status'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.CheckConstraint(check=models.Q(('process_loss__gt', 0)), name='chk_recipe_version_process_loss'),
        ),
        migrations.AddIndex(
            model_name='recipecomponent',
            index=models.Index(fields=['component_product'], name='idx_component_product'),
        ),
        migrations.AddConstraint(
            model_name='recipecomponent',
            constraint=models.UniqueConstraint(fields=('recipe_version', 'component_product'), name='uq_version_component'),
        ),
        migrations.AddConstraint(
            model_name='recipecomponent',
            constraint=models.UniqueConstraint(fields=('recipe_version', 'line_no'), name='uq_version_line_no'),
        ),
        migrations.AddConstraint(
            model_name='recipecomponent',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='chk_recipe_component_qty'),
        ),
    ]
