# Generated by Django 4.2.30 on 2026-08-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_recipe_schema_chunk3'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeversion',
            name='chk_recipe_version_status',
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_by_sub',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='approval_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='approved_by_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='approved_by_sub',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='created_by_sub',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='rejected_by_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='rejected_by_sub',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='submitted_by_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='submitted_by_sub',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='recipeversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=16),
        ),
        migrations.AddIndex(
            model_name='recipeversion',
            index=models.Index(fields=['status', 'effective_from'], name='idx_recipe_version_due'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['draft', 'pending_approval', 'rejected', 'approved', 'active', 'retired'])), name='chk_recipe_version_status'),
        ),
    ]
