# Generated by Django 4.2.30 on 2026-08-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_ops_error_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=16, unique=True)),
                ('min_version', models.CharField(max_length=32)),
                ('latest_version', models.CharField(blank=True, default='', max_length=32)),
                ('message', models.CharField(blank=True, default='', max_length=256)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_version',
            },
        ),
    ]
