# Generated by Django 4.2.30 on 2026-07-27 14:38

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_loc_edge_relation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'product_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryState',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'product_delivery_state',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackagingType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'product_packaging_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalState',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'product_physical_state',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('alternate_name', models.CharField(blank=True, max_length=128, null=True)),
                ('recipe_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('alternate_recipe_code', models.CharField(blank=True, max_length=32, null=True)),
                ('gff_code', models.CharField(blank=True, max_length=32, null=True)),
                ('secondary_gff_recipe', models.CharField(blank=True, max_length=32, null=True)),
                ('external_barcode', models.CharField(blank=True, max_length=16, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_downtime', models.BooleanField(default=False)),
                ('purchasing_version', models.IntegerField(blank=True, null=True)),
                ('ingredient_count', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.category')),
                ('destination_container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_products', to='locations.location')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'product_class',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseShapeFormat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'product_purchase_shape_format',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'product_range',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'product_unit',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAudit',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='audit', serialize=False, to='product.product')),
                ('created_by_user_id', models.IntegerField(blank=True, null=True)),
                ('lan_username', models.CharField(blank=True, max_length=64, null=True)),
                ('source_workstation', models.CharField(blank=True, max_length=64, null=True)),
                ('source_workstation_ip', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'product_audit',
            },
        ),
        migrations.CreateModel(
            name='ProductCosting',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='costing', serialize=False, to='product.product')),
                ('unit_cost', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16)),
                ('unit_price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16)),
                ('nominal_code', models.CharField(blank=True, max_length=4, null=True)),
                ('case_size_description', models.CharField(blank=True, max_length=64, null=True)),
                ('lead_time_days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_costing',
            },
        ),
        migrations.CreateModel(
            name='ProductFlags',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='flags', serialize=False, to='product.product')),
                ('in_stock_list', models.BooleanField(default=False)),
                ('auto_yield', models.BooleanField(default=False)),
                ('has_plan', models.BooleanField(default=False)),
                ('auto_rate', models.BooleanField(default=False)),
                ('auto_clear_stock', models.BooleanField(default=False)),
                ('consider_stock_in_plan', models.BooleanField(default=False)),
                ('has_recipe', models.BooleanField(default=False)),
                ('full_batches_only', models.BooleanField(default=False)),
                ('auto_trends', models.BooleanField(default=False)),
                ('is_implicit', models.BooleanField(default=False)),
                ('include_in_projections', models.BooleanField(default=False)),
                ('record_flag', models.BooleanField(default=False)),
                ('has_chilling_loss', models.BooleanField(default=False)),
                ('use_batch_quantity', models.BooleanField(default=False)),
                ('freezer_no_deduct', models.BooleanField(default=False)),
                ('is_purchase_item', models.BooleanField(default=False)),
                ('is_sales_item', models.BooleanField(default=False)),
                ('is_dispatch_support', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'product_flags',
            },
        ),
        migrations.CreateModel(
            name='ProductProduction',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='production', serialize=False, to='product.product')),
                ('avg_run_size', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('avg_minutes', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('avg_rate_product', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('avg_staff_min_per_unit', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('avg_staff_per_minute', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('avg_rate_range', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('average_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('unitary_gap_time', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('unitary_dwell_time', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('relative_plan_position', models.IntegerField(blank=True, null=True)),
                ('default_resource_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_production',
            },
        ),
        migrations.CreateModel(
            name='ProductShelfLife',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shelf_life', serialize=False, to='product.product')),
                ('shelf_life_days', models.IntegerField(blank=True, null=True)),
                ('shelf_life_intrinsic_days', models.IntegerField(blank=True, null=True)),
                ('shelf_life_depot_days', models.IntegerField(blank=True, null=True)),
                ('absolute_min_shelf_life_days', models.IntegerField(blank=True, null=True)),
                ('force_production_date', models.BooleanField(default=False)),
                ('force_trace_number', models.BooleanField(default=False)),
                ('force_use_by', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'product_shelf_life',
            },
        ),
        migrations.CreateModel(
            name='ProductStockPolicy',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stock_policy', serialize=False, to='product.product')),
                ('reorder_level', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('min_stock', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('max_stock', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('clear_stock_level', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
            ],
            options={
                'db_table': 'product_stock_policy',
            },
        ),
        migrations.CreateModel(
            name='ProductTechnical',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='technical', serialize=False, to='product.product')),
                ('is_gmo_free', models.BooleanField(default=False)),
                ('spec_sign_off_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('requires_temperature_check', models.BooleanField(default=False)),
                ('temp_check_lower_bound', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('temp_check_upper_bound', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'product_technical',
            },
        ),
        migrations.CreateModel(
            name='ProductYield',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='yield_data', serialize=False, to='product.product')),
                ('yield_factor', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10)),
                ('yield_factor_auto', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10)),
                ('chilling_loss_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'product_yield',
            },
        ),
        migrations.CreateModel(
            name='SubRange',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_sub_ranges', to='product.range')),
            ],
            options={
                'db_table': 'product_sub_range',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.productclass'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_shape_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.purchaseshapeformat'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchasing_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchased_products', to='product.unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.range'),
        ),
        migrations.AddField(
            model_name='product',
            name='source_container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_products', to='locations.location'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.subrange'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.unit'),
        ),
        migrations.CreateModel(
            name='ProductPackaging',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='packaging', serialize=False, to='product.product')),
                ('pack_weight', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('unitary_weight', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('gross_unitary_weight', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('align_unitary_weight', models.BooleanField(default=False)),
                ('default_length', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('items_per_unit', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('units_per_tray', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('units_per_batch', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('is_gas_flush', models.BooleanField(default=False)),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='box_packaged_products', to='locations.location')),
                ('container_vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vessel_packaged_products', to='locations.location')),
                ('delivery_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.deliverystate')),
                ('packaging_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.packagingtype')),
                ('physical_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.physicalstate')),
                ('tray', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tray_packaged_products', to='locations.location')),
            ],
            options={
                'db_table': 'product_packaging',
            },
        ),
    ]
