# Generated by Django 4.2.30 on 2026-07-27 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_product_schema_chunk4'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAcceptance',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='acceptance', serialize=False, to='product.product')),
                ('min_acceptable_shelf_life_days', models.IntegerField(blank=True, null=True)),
                ('acceptance_note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_acceptance',
            },
        ),
        migrations.CreateModel(
            name='ProductIngredientLabel',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ingredient_label', serialize=False, to='product.product')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('per_srp', models.CharField(blank=True, max_length=64, null=True)),
                ('per_box', models.CharField(blank=True, max_length=64, null=True)),
                ('free_text_a', models.TextField(blank=True, null=True)),
                ('free_text_b', models.TextField(blank=True, null=True)),
                ('size_text', models.CharField(blank=True, max_length=64, null=True)),
                ('storage', models.TextField(blank=True, null=True)),
                ('cooking_preparation', models.TextField(blank=True, null=True)),
                ('average_weight', models.CharField(blank=True, max_length=64, null=True)),
                ('per_pallet', models.CharField(blank=True, max_length=64, null=True)),
                ('per_case', models.CharField(blank=True, max_length=64, null=True)),
                ('ingredients_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_ingredient_label',
            },
        ),
        migrations.CreateModel(
            name='ProductNutrition',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nutrition', serialize=False, to='product.product')),
                ('energy_kj', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('energy_kcal', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('saturates_g', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('carbohydrate_g', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('sugars_g', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('fibre_g', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('salt_g', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'product_nutrition',
            },
        ),
        migrations.AddField(
            model_name='producttechnical',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='producttechnical',
            name='is_vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producttechnical',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductAllergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen_code', models.CharField(choices=[('none', 'None'), ('celery', 'Celery'), ('crustaceans', 'Crustaceans'), ('eggs', 'Eggs'), ('fish', 'Fish'), ('gluten', 'Gluten'), ('lupin', 'Lupin'), ('milk', 'Milk'), ('molluscs', 'Molluscs'), ('mustard', 'Mustard'), ('nuts', 'Nuts'), ('peanuts', 'Peanuts'), ('sesame', 'Sesame'), ('soya', 'Soya'), ('sulphites', 'Sulphites')], max_length=16)),
                ('contains', models.BooleanField(default=False)),
                ('may_contain', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergens', to='product.product')),
            ],
            options={
                'db_table': 'product_allergen',
            },
        ),
        migrations.AddConstraint(
            model_name='productallergen',
            constraint=models.UniqueConstraint(fields=('product', 'allergen_code'), name='uniq_product_allergen_code'),
        ),
    ]
