# Generated by Django 4.2.30 on 2026-07-30 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productacceptance_productingredientlabel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpackaging',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packaging_as_box', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='container_vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packaging_as_container_vessel', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='tray',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packaging_as_tray', to='product.product'),
        ),
    ]
