# Generated by Django 4.2.30 on 2026-07-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productpackaging_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productaudit',
            name='actor_email',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productaudit',
            name='actor_sub',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productaudit',
            name='timeline_events',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='productaudit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='lan_username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='source_workstation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
