# Generated by Django 4.2.30 on 2026-07-30 12:01

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_loc_edge_relation_type'),
        ('product', '0004_productaudit_actor_email_productaudit_actor_sub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(max_length=64)),
                ('supplier_product_name', models.CharField(max_length=128)),
                ('cost', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16)),
                ('conversion_to_base', models.DecimalField(decimal_places=6, max_digits=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pack_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_products', to='product.unit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='product.product')),
                ('purchase_shape_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_products', to='product.purchaseshapeformat')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplied_products', to='locations.location')),
            ],
            options={
                'db_table': 'product_supplier',
                'indexes': [models.Index(fields=['supplier'], name='idx_product_supplier_supplier')],
            },
        ),
        migrations.AddConstraint(
            model_name='productsupplier',
            constraint=models.UniqueConstraint(fields=('product', 'supplier', 'supplier_code'), name='uniq_product_supplier_code'),
        ),
        migrations.AddConstraint(
            model_name='productsupplier',
            constraint=models.CheckConstraint(check=models.Q(('conversion_to_base__gt', 0)), name='chk_product_supplier_conversion_positive'),
        ),
    ]
