# Generated by Django 4.2.30 on 2026-07-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_id_autofield'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='to_base_factor',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Multiply by this to convert to the base unit of the group.', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_group',
            field=models.CharField(blank=True, choices=[('count', 'Count'), ('weight', 'Weight'), ('liquid', 'Liquid')], max_length=8, null=True),
        ),
    ]
