# Generated by Django 4.2.30 on 2026-07-31 10:23

import django.db.models.deletion
from django.db import migrations, models


def _add_if_missing(schema_editor, column, sql):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT COUNT(*) FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = 'product_category'
              AND COLUMN_NAME = %s
            """,
            [column],
        )
        if cursor.fetchone()[0] == 0:
            cursor.execute(sql)


def apply_expand(apps, schema_editor):
    # Idempotent: local DB may already have parent_id (deleted 0003) and/or a
    # partial failed apply of this migration.
    adds = [
        ('code_generator', 'ALTER TABLE product_category ADD COLUMN code_generator varchar(256) NULL'),
        ('code_generator_path', 'ALTER TABLE product_category ADD COLUMN code_generator_path varchar(256) NULL'),
        ('is_container', 'ALTER TABLE product_category ADD COLUMN is_container tinyint(1) NULL'),
        ('is_container_flag', 'ALTER TABLE product_category ADD COLUMN is_container_flag tinyint(1) NOT NULL DEFAULT 0'),
        ('is_default', 'ALTER TABLE product_category ADD COLUMN is_default tinyint(1) NOT NULL DEFAULT 0'),
        ('is_locked', 'ALTER TABLE product_category ADD COLUMN is_locked tinyint(1) NOT NULL DEFAULT 0'),
        ('is_locked_assigned', 'ALTER TABLE product_category ADD COLUMN is_locked_assigned tinyint(1) NOT NULL DEFAULT 0'),
        ('is_locked_path', 'ALTER TABLE product_category ADD COLUMN is_locked_path tinyint(1) NOT NULL DEFAULT 0'),
        ('is_other', 'ALTER TABLE product_category ADD COLUMN is_other tinyint(1) NOT NULL DEFAULT 0'),
        ('is_range', 'ALTER TABLE product_category ADD COLUMN is_range tinyint(1) NOT NULL DEFAULT 0'),
        ('is_resource', 'ALTER TABLE product_category ADD COLUMN is_resource tinyint(1) NOT NULL DEFAULT 0'),
        ('item_flag', 'ALTER TABLE product_category ADD COLUMN item_flag smallint NOT NULL DEFAULT -1'),
        ('last_increment_auto_code', 'ALTER TABLE product_category ADD COLUMN last_increment_auto_code int NOT NULL DEFAULT 0'),
        ('multiplier', 'ALTER TABLE product_category ADD COLUMN multiplier decimal(10,2) NULL'),
        ('parent_id', 'ALTER TABLE product_category ADD COLUMN parent_id int NULL'),
        ('path', 'ALTER TABLE product_category ADD COLUMN path varchar(256) NULL'),
        ('path_nodes', 'ALTER TABLE product_category ADD COLUMN path_nodes varchar(128) NULL'),
        ('purchase_unit_id', 'ALTER TABLE product_category ADD COLUMN purchase_unit_id int NULL'),
        ('remarks', 'ALTER TABLE product_category ADD COLUMN remarks longtext NULL'),
    ]
    for column, sql in adds:
        _add_if_missing(schema_editor, column, sql)

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            'ALTER TABLE product_category MODIFY COLUMN name varchar(256) NOT NULL'
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_id_autofield'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='category',
                    name='code_generator',
                    field=models.CharField(blank=True, max_length=256, null=True),
                ),
                migrations.AddField(
                    model_name='category',
                    name='code_generator_path',
                    field=models.CharField(blank=True, max_length=256, null=True),
                ),
                migrations.AddField(
                    model_name='category',
                    name='is_container',
                    field=models.BooleanField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='category',
                    name='is_container_flag',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='category',
                    name='is_default',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='category',
                    name='is_locked',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='category',
                    name='is_locked_assigned',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='category',
                    name='is_locked_path',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='category',
                    name='is_other',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='category',
                    name='is_range',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='category',
                    name='is_resource',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='category',
                    name='item_flag',
                    field=models.SmallIntegerField(default=-1),
                ),
                migrations.AddField(
                    model_name='category',
                    name='last_increment_auto_code',
                    field=models.IntegerField(default=0),
                ),
                migrations.AddField(
                    model_name='category',
                    name='multiplier',
                    field=models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                migrations.AddField(
                    model_name='category',
                    name='parent',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='children',
                        to='product.category',
                    ),
                ),
                migrations.AddField(
                    model_name='category',
                    name='path',
                    field=models.CharField(blank=True, max_length=256, null=True),
                ),
                migrations.AddField(
                    model_name='category',
                    name='path_nodes',
                    field=models.CharField(blank=True, max_length=128, null=True),
                ),
                migrations.AddField(
                    model_name='category',
                    name='purchase_unit',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='purchase_unit_categories',
                        to='product.unit',
                    ),
                ),
                migrations.AddField(
                    model_name='category',
                    name='remarks',
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AlterField(
                    model_name='category',
                    name='name',
                    field=models.CharField(max_length=256),
                ),
            ],
            database_operations=[
                migrations.RunPython(apply_expand, noop_reverse),
            ],
        ),
    ]
