# Generated by Django 4.2.30 on 2026-08-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_expand_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label_mode',
            field=models.CharField(choices=[('product', 'Reusable product label, FIFO picked on scan'), ('batch', 'One label per batch'), ('per_unit', 'One label per physical unit')], default='product', max_length=16),
        ),
    ]
