# Generated by Django 4.2.30 on 2026-08-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_range_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='goods_in_type',
            field=models.CharField(blank=True, choices=[('raw_material', 'Raw material'), ('packaging', 'Packaging'), ('other', 'Other')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='producttechnical',
            name='storage_regime',
            field=models.CharField(blank=True, choices=[('ambient', 'Ambient'), ('chilled', 'Chilled'), ('frozen', 'Frozen'), ('non_food', 'Non-food')], max_length=16, null=True),
        ),
    ]
