# Generated by Django 4.2.13 on 2026-09-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_buy_type_lookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='goods_out_pack_qty',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('goods_out_pack_qty__isnull', True), ('goods_out_pack_qty__gt', 0), _connector='OR'), name='chk_product_goods_out_pack_qty_pos'),
        ),
    ]
