# Generated by Django 4.2.30 on 2026-08-19 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_rbac', '0003_department_it'),
        ('hardware', '0003_last_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwaredevice',
            name='last_screen',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='HardwareDeviceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('body', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_messages', to='users_rbac.rbacuser')),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hardware.hardwaredevice')),
            ],
            options={
                'db_table': 'hw_device_message',
                'ordering': ['-created_at'],
            },
        ),
    ]
