# Generated by Django 4.2.30 on 2026-08-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_last_screen_and_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwaredevicepost',
            name='metadata_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
