# Generated by Django 4.2.30 on 2026-08-03 11:56

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_loc_edge_relation_type'),
        ('recipe', '0001_recipe_schema_chunk3'),
        ('stock_ledger', '0006_unit_conversion_chunk8'),
        ('product', '0008_expand_category'),
        ('planning', '0002_plan_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], default='draft', max_length=16)),
                ('quantity_made', models.DecimalField(decimal_places=6, max_digits=16)),
                ('shift', models.CharField(blank=True, max_length=32, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('production_date', models.DateField()),
                ('use_by', models.DateField(blank=True, null=True)),
                ('trace_number', models.CharField(blank=True, max_length=64, null=True)),
                ('staff_count', models.IntegerField(blank=True, null=True)),
                ('trays', models.IntegerField(blank=True, null=True)),
                ('batches', models.IntegerField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True)),
                ('actor_user_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs_from', to='locations.location')),
                ('output_stock_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_run_outputs', to='stock_ledger.stockentry')),
                ('plan_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='planning.planline')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='product.product')),
                ('recipe_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='recipe.recipeversion')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='planning.resource')),
            ],
            options={
                'db_table': 'prod_reg_run',
            },
        ),
        migrations.CreateModel(
            name='ProductionStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('default_consume_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_station_consumes', to='locations.location')),
                ('default_output_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_station_outputs', to='locations.location')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_stations', to='locations.location')),
            ],
            options={
                'db_table': 'prod_reg_station',
            },
        ),
        migrations.CreateModel(
            name='ProductionRunConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=16)),
                ('needed_qty', models.DecimalField(decimal_places=6, max_digits=16)),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_run_consumptions', to='product.product')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_run_consumptions', to='stock_ledger.stocklot')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='production_register.productionrun')),
                ('stock_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_run_consumptions', to='stock_ledger.stockentry')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_run_consumptions', to='product.unit')),
            ],
            options={
                'db_table': 'prod_reg_run_consumption',
            },
        ),
        migrations.AddField(
            model_name='productionrun',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='production_register.productionstation'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs_to', to='locations.location'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='product.unit'),
        ),
        migrations.CreateModel(
            name='ProductionDowntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=32, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_downtimes', to='planning.resource')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtimes', to='production_register.productionstation')),
            ],
            options={
                'db_table': 'prod_reg_downtime',
            },
        ),
        migrations.AddConstraint(
            model_name='productionstation',
            constraint=models.CheckConstraint(check=models.Q(('code__in', ['high_risk', 'sleeving', 'internal_process', 'warehouse'])), name='chk_prod_reg_station_code'),
        ),
        migrations.AddIndex(
            model_name='productionrunconsumption',
            index=models.Index(fields=['run'], name='idx_prod_reg_consumption_run'),
        ),
        migrations.AddConstraint(
            model_name='productionrunconsumption',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', Decimal('0'))), name='chk_prod_reg_consumption_qty'),
        ),
        migrations.AddConstraint(
            model_name='productionrunconsumption',
            constraint=models.CheckConstraint(check=models.Q(('needed_qty__gte', Decimal('0'))), name='chk_prod_reg_consumption_needed'),
        ),
        migrations.AddIndex(
            model_name='productionrun',
            index=models.Index(fields=['station', 'status', 'production_date'], name='idx_prod_reg_run_station'),
        ),
        migrations.AddIndex(
            model_name='productionrun',
            index=models.Index(fields=['production_date', 'status'], name='idx_prod_reg_run_date'),
        ),
        migrations.AddConstraint(
            model_name='productionrun',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['draft', 'posted', 'void'])), name='chk_prod_reg_run_status'),
        ),
        migrations.AddConstraint(
            model_name='productionrun',
            constraint=models.CheckConstraint(check=models.Q(('quantity_made__gt', Decimal('0'))), name='chk_prod_reg_run_qty'),
        ),
        migrations.AddConstraint(
            model_name='productionrun',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('idempotency_key',), name='uq_prod_reg_run_idempotency'),
        ),
        migrations.AddIndex(
            model_name='productiondowntime',
            index=models.Index(fields=['station', 'start_at'], name='idx_prod_reg_downtime_station'),
        ),
    ]
