# Generated by Django 4.2.30 on 2026-08-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_register', '0001_prod_reg_schema_chunk4'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productionstation',
            name='chk_prod_reg_station_code',
        ),
    ]
