# Generated by Django 4.2.30 on 2026-08-10 16:22

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0013_product_goods_in_masters'),
        ('locations', '0004_supplier_approval_quarantine'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('partial', 'Partial'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('ordered_at', models.DateField(blank=True, null=True)),
                ('expected_at', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=256, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('legacy_csv', 'Legacy CSV'), ('sage', 'Sage')], default='manual', max_length=16)),
                ('external_number', models.CharField(blank=True, max_length=64, null=True)),
                ('delivery_trace_number', models.CharField(blank=True, max_length=64, null=True)),
                ('vehicle_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('reject_delivery', models.BooleanField(default=False)),
                ('header_checks', models.JSONField(blank=True, default=dict)),
                ('header_template_id', models.BigIntegerField(blank=True, null=True)),
                ('header_template_version', models.IntegerField(blank=True, null=True)),
                ('checked_by_user_id', models.IntegerField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('qc_tl_checked_by_user_id', models.IntegerField(blank=True, null=True)),
                ('qc_tl_checked_at', models.DateTimeField(blank=True, null=True)),
                ('qc_tl_comment', models.TextField(blank=True, null=True)),
                ('total_net', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('created_by_user_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ship_to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_purchase_orders', to='locations.location')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='locations.location')),
            ],
            options={
                'db_table': 'po_purchase_order',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('non_conformance', 'Non-conformance'), ('note', 'Note')], max_length=32)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor_user_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='purchasing.purchaseorder')),
            ],
            options={
                'db_table': 'po_purchase_order_history',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('qty_ordered', models.DecimalField(decimal_places=6, max_digits=16)),
                ('qty_received', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16)),
                ('qty_balance', models.DecimalField(decimal_places=6, max_digits=16)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('multiplier', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('shape_format_label', models.CharField(blank=True, max_length=128, null=True)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('use_by', models.DateField(blank=True, null=True)),
                ('trace_number', models.CharField(blank=True, max_length=64, null=True)),
                ('product_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('line_checks', models.JSONField(blank=True, default=dict)),
                ('line_template_id', models.BigIntegerField(blank=True, null=True)),
                ('line_template_version', models.IntegerField(blank=True, null=True)),
                ('line_check_ok', models.BooleanField(default=False)),
                ('line_closed', models.BooleanField(default=False)),
                ('stock_in_done', models.BooleanField(default=False)),
                ('last_receipt_entry_id', models.BigIntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='product.product')),
                ('product_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='product.productsupplier')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseorder')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='product.unit')),
            ],
            options={
                'db_table': 'po_purchase_order_line',
                'ordering': ['purchase_order_id', 'line_no'],
                'indexes': [models.Index(fields=['product'], name='idx_po_line_product'), models.Index(fields=['purchase_order', 'line_closed'], name='idx_po_line_open')],
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'line_no'), name='uniq_po_line_no'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(check=models.Q(('qty_ordered__gt', 0)), name='chk_po_line_qty_ordered_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(check=models.Q(('qty_received__gte', 0)), name='chk_po_line_qty_received_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(check=models.Q(('qty_balance__gte', 0)), name='chk_po_line_qty_balance_nonneg'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderhistory',
            index=models.Index(fields=['purchase_order', 'created_at'], name='idx_po_history_po_created'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='idx_po_status'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier'], name='idx_po_supplier'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['expected_at'], name='idx_po_expected_at'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['draft', 'ordered', 'partial', 'received', 'cancelled'])), name='chk_po_status'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(check=models.Q(('source__in', ['manual', 'legacy_csv', 'sage'])), name='chk_po_source'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(condition=models.Q(('external_number__isnull', False)), fields=('source', 'external_number'), name='uniq_po_source_external_number'),
        ),
    ]
