# Generated by Django 4.2.30 on 2026-08-10 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_po_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=256)),
                ('input_type', models.CharField(choices=[('bool', 'Yes/No'), ('decimal', 'Decimal'), ('text', 'Text'), ('date', 'Date')], max_length=16)),
                ('required', models.BooleanField(default=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('fail_when', models.CharField(blank=True, choices=[('false', 'Fail when false'), ('true', 'Fail when true'), ('out_of_range', 'Fail when out of range')], max_length=16, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('source', models.CharField(blank=True, max_length=64, null=True)),
                ('allows_comment', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'po_goods_in_check_item',
                'ordering': ['template_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsInCheckTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('goods_in_type', models.CharField(max_length=16)),
                ('storage_regime', models.CharField(blank=True, max_length=16, null=True)),
                ('scope', models.CharField(choices=[('header', 'Header'), ('line', 'Line')], max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('document_no', models.CharField(default='GFF001F', max_length=32)),
                ('issue_no', models.PositiveIntegerField(default=15)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('previous_issue_date', models.DateField(blank=True, null=True)),
                ('reason_for_change', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'po_goods_in_check_template',
                'ordering': ['goods_in_type', 'scope', '-version'],
                'indexes': [models.Index(fields=['goods_in_type', 'storage_regime', 'scope', 'is_active'], name='idx_goods_in_template_lookup')],
            },
        ),
        migrations.AddConstraint(
            model_name='goodsinchecktemplate',
            constraint=models.UniqueConstraint(fields=('goods_in_type', 'storage_regime', 'scope', 'version'), name='uniq_goods_in_template_key_version'),
        ),
        migrations.AddConstraint(
            model_name='goodsinchecktemplate',
            constraint=models.CheckConstraint(check=models.Q(('scope__in', ['header', 'line'])), name='chk_goods_in_template_scope'),
        ),
        migrations.AddField(
            model_name='goodsincheckitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.goodsinchecktemplate'),
        ),
        migrations.AddConstraint(
            model_name='goodsincheckitem',
            constraint=models.UniqueConstraint(fields=('template', 'code'), name='uniq_goods_in_item_code'),
        ),
        migrations.AddConstraint(
            model_name='goodsincheckitem',
            constraint=models.CheckConstraint(check=models.Q(('input_type__in', ['bool', 'decimal', 'text', 'date'])), name='chk_goods_in_item_input_type'),
        ),
    ]
