# Generated by Django 4.2.30 on 2026-08-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_goods_in_check_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
