# Generated by Django 4.2.30 on 2026-08-10 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_po_delivery_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('coa', 'COA/COC'), ('delivery_note', 'Delivery note'), ('other', 'Other')], default='photo', max_length=32)),
                ('s3_key', models.CharField(max_length=512)),
                ('content_type', models.CharField(blank=True, max_length=64, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_by_user_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='purchasing.purchaseorderhistory')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='purchasing.purchaseorderline')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='purchasing.purchaseorder')),
            ],
            options={
                'db_table': 'po_goods_in_attachment',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['purchase_order', 'kind'], name='idx_po_attachment_po_kind')],
            },
        ),
    ]
