# Generated by Django 4.2.30 on 2026-08-29 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_widen_contact_phone_email'),
        ('product', '0017_productsupplier_sage_product_code'),
        ('purchasing', '0007_po_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderhistory',
            name='event_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('accept', 'Accept'), ('reject', 'Reject'), ('non_conformance', 'Non-conformance'), ('note', 'Note')], max_length=32),
        ),
        migrations.CreateModel(
            name='AdhocGoodsInSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('rejected', 'Rejected'), ('qc_complete', 'QC complete')], default='open', max_length=16)),
                ('delivery_at', models.DateField(blank=True, null=True)),
                ('delivery_trace_number', models.CharField(blank=True, max_length=64, null=True)),
                ('vehicle_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('reject_delivery', models.BooleanField(default=False)),
                ('header_checks', models.JSONField(blank=True, default=dict)),
                ('header_template_id', models.BigIntegerField(blank=True, null=True)),
                ('header_template_version', models.IntegerField(blank=True, null=True)),
                ('checked_by_user_id', models.IntegerField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('qc_tl_checked_by_user_id', models.IntegerField(blank=True, null=True)),
                ('qc_tl_checked_at', models.DateTimeField(blank=True, null=True)),
                ('qc_tl_comment', models.TextField(blank=True, null=True)),
                ('created_by_user_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adhoc_goods_in_sessions', to='locations.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adhoc_goods_in_sessions', to='product.product')),
            ],
            options={
                'db_table': 'po_adhoc_goods_in_session',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AdhocGoodsInLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField(blank=True, null=True)),
                ('use_by', models.DateField(blank=True, null=True)),
                ('trace_number', models.CharField(blank=True, max_length=64, null=True)),
                ('product_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('line_checks', models.JSONField(blank=True, default=dict)),
                ('line_template_id', models.BigIntegerField(blank=True, null=True)),
                ('line_template_version', models.IntegerField(blank=True, null=True)),
                ('line_check_ok', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adhoc_goods_in_lines', to='product.product')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='line', to='purchasing.adhocgoodsinsession')),
            ],
            options={
                'db_table': 'po_adhoc_goods_in_line',
            },
        ),
        migrations.AddIndex(
            model_name='adhocgoodsinsession',
            index=models.Index(fields=['status', 'created_at'], name='idx_adhoc_gin_status_created'),
        ),
        migrations.AddIndex(
            model_name='adhocgoodsinsession',
            index=models.Index(fields=['product', 'status'], name='idx_adhoc_gin_product_status'),
        ),
        migrations.AddConstraint(
            model_name='adhocgoodsinsession',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['open', 'rejected', 'qc_complete'])), name='chk_adhoc_gin_status'),
        ),
    ]
