# Generated by Django 4.2.30 on 2026-08-29 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_productsupplier_sage_product_code'),
        ('purchasing', '0008_adhoc_goods_in'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adhocgoodsinsession',
            name='chk_adhoc_gin_status',
        ),
        migrations.AddField(
            model_name='adhocgoodsinline',
            name='last_receipt_entry_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adhocgoodsinline',
            name='product_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adhoc_goods_in_lines', to='product.productsupplier'),
        ),
        migrations.AddField(
            model_name='adhocgoodsinline',
            name='qty_entered',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='adhocgoodsinline',
            name='shape_format_label',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='adhocgoodsinline',
            name='shape_other',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adhocgoodsinline',
            name='stock_qty',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='adhocgoodsinsession',
            name='item_po_ref',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='adhocgoodsinsession',
            name='label_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adhocgoodsinsession',
            name='label_format',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='adhocgoodsinsession',
            name='receive_idempotency_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='adhocgoodsinsession',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('rejected', 'Rejected'), ('qc_complete', 'QC complete'), ('received', 'Received')], default='open', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='adhocgoodsinsession',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['open', 'rejected', 'qc_complete', 'received'])), name='chk_adhoc_gin_status'),
        ),
    ]
