# Generated by Django 4.2.30 on 2026-09-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0013_po_amend_revision'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='goodsinanswer',
            name='chk_gin_answer_parent',
        ),
        migrations.RemoveConstraint(
            model_name='purchaseorderdelivery',
            name='chk_po_delivery_status',
        ),
        migrations.AlterField(
            model_name='purchaseorderdelivery',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('rejected', 'Rejected'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='open', max_length=16),
        ),
        migrations.AlterField(
            model_name='purchaseorderhistory',
            name='event_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('amend', 'Amend'), ('accept', 'Accept'), ('reject', 'Reject'), ('cancel', 'Cancel'), ('non_conformance', 'Non-conformance'), ('note', 'Note')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderdelivery',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['open', 'rejected', 'received', 'cancelled'])), name='chk_po_delivery_status'),
        ),
        migrations.AddConstraint(
            model_name='goodsinanswer',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('adhoc_line_id__isnull', True), ('adhoc_session_id__isnull', True), ('delivery_id__isnull', False), models.Q(models.Q(('delivery_line_id__isnull', True), ('scope', 'header')), models.Q(('delivery_line_id__isnull', False), ('scope', 'line')), _connector='OR')), models.Q(('adhoc_session_id__isnull', False), ('delivery_id__isnull', True), ('delivery_line_id__isnull', True), models.Q(models.Q(('adhoc_line_id__isnull', True), ('scope', 'header')), models.Q(('adhoc_line_id__isnull', False), ('scope', 'line')), _connector='OR')), _connector='OR'), name='chk_gin_answer_parent'),
        ),
    ]
