# Generated by Django 4.2.30 on 2026-07-28 15:10

from decimal import Decimal

from django.db import migrations, models
from django.utils import timezone
import django.db.models.deletion


def seed_stock_chain_head(apps, schema_editor):
    StockChainHead = apps.get_model('stock_ledger', 'StockChainHead')
    StockChainHead.objects.get_or_create(
        id=1,
        defaults={
            'entry_count': 0,
            'updated_at': timezone.now(),
        },
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_productacceptance_productingredientlabel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockChainHead',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('head_entry_id', models.BigIntegerField(blank=True, null=True)),
                ('head_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('entry_count', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'stock_chain_head',
            },
        ),
        migrations.CreateModel(
            name='StockPeriod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=8)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by_user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_period',
            },
        ),
        migrations.CreateModel(
            name='StockUnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_kg', models.DecimalField(decimal_places=6, max_digits=16)),
                ('source', models.CharField(max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_unit_conversions', to='product.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_unit_conversions', to='product.unit')),
            ],
            options={
                'db_table': 'stock_unit_conversion',
            },
        ),
        migrations.AddConstraint(
            model_name='stockperiod',
            constraint=models.UniqueConstraint(fields=('period_start', 'period_end'), name='uq_stock_period_range'),
        ),
        migrations.AddConstraint(
            model_name='stockperiod',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['open', 'closed'])), name='chk_stock_period_status'),
        ),
        migrations.AddConstraint(
            model_name='stockperiod',
            constraint=models.CheckConstraint(check=models.Q(('period_end__gte', models.F('period_start'))), name='chk_stock_period_order'),
        ),
        migrations.AddConstraint(
            model_name='stockchainhead',
            constraint=models.CheckConstraint(check=models.Q(('id', 1)), name='chk_stock_chain_head_singleton'),
        ),
        migrations.AddConstraint(
            model_name='stockunitconversion',
            constraint=models.UniqueConstraint(fields=('unit', 'product'), name='uq_stock_unit_conversion'),
        ),
        migrations.AddConstraint(
            model_name='stockunitconversion',
            constraint=models.CheckConstraint(check=models.Q(('to_kg__gt', Decimal('0'))), name='chk_stock_unit_conversion_pos'),
        ),
        migrations.RunPython(seed_stock_chain_head, migrations.RunPython.noop),
    ]
