# Generated by Django 4.2.30 on 2026-07-28 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_recipe_schema_chunk3'),
        ('product', '0002_productacceptance_productingredientlabel_and_more'),
        ('stock_ledger', '0001_foundation_models_chunk3'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_number', models.CharField(max_length=32)),
                ('supplier_lot_code', models.CharField(blank=True, max_length=64, null=True)),
                ('origin', models.CharField(choices=[('production', 'Production'), ('purchase', 'Purchase'), ('opening', 'Opening')], max_length=16)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('use_by', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='product.product')),
                ('recipe_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='recipe.recipeversion')),
                ('shape_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='product.purchaseshapeformat')),
            ],
            options={
                'db_table': 'stock_lot',
            },
        ),
        migrations.CreateModel(
            name='StockLotAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('use_by', 'Use by'), ('production_date', 'Production date'), ('supplier_lot_code', 'Supplier lot code')], max_length=32)),
                ('old_value', models.CharField(blank=True, max_length=64, null=True)),
                ('new_value', models.CharField(blank=True, max_length=64, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('authorised_by_user_id', models.IntegerField()),
                ('effective_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='stock_ledger.stocklot')),
            ],
            options={
                'db_table': 'stock_lot_amendment',
                'indexes': [models.Index(fields=['lot', 'recorded_at'], name='idx_stock_lot_amendment_lot')],
            },
        ),
        migrations.AddConstraint(
            model_name='stocklotamendment',
            constraint=models.CheckConstraint(check=models.Q(('field_name__in', ['use_by', 'production_date', 'supplier_lot_code'])), name='chk_stock_lot_amendment_field'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['product', 'use_by'], name='idx_stock_lot_product_useby'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['trace_number'], name='idx_stock_lot_trace'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.UniqueConstraint(fields=('product', 'trace_number', 'production_date', 'use_by', 'recipe_version', 'shape_format'), name='uq_stock_lot_identity'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.CheckConstraint(check=models.Q(('origin__in', ['production', 'purchase', 'opening'])), name='chk_stock_lot_origin'),
        ),
    ]
