# Generated by Django 4.2.30 on 2026-07-28 15:19

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_loc_edge_relation_type'),
        ('product', '0002_productacceptance_productingredientlabel_and_more'),
        ('stock_ledger', '0002_lot_models_chunk4'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=64)),
                ('entry_type', models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('transfer_out', 'Transfer out'), ('transfer_in', 'Transfer in'), ('production_output', 'Production output'), ('production_consumption', 'Production consumption'), ('count_adjustment', 'Count adjustment'), ('disposal', 'Disposal'), ('reversal', 'Reversal')], max_length=24)),
                ('transfer_group_id', models.CharField(blank=True, max_length=36, null=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=16)),
                ('base_unit_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('quantity_base', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('effective_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField()),
                ('override_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('authorised_by_user_id', models.IntegerField(blank=True, null=True)),
                ('source_document_type', models.CharField(blank=True, max_length=24, null=True)),
                ('source_document_id', models.BigIntegerField(blank=True, null=True)),
                ('source_document_line', models.IntegerField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('line_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('actor_user_id', models.IntegerField(blank=True, null=True)),
                ('lan_username', models.CharField(blank=True, max_length=64, null=True)),
                ('source_workstation', models.CharField(blank=True, max_length=64, null=True)),
                ('source_workstation_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('prev_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('entry_hash', models.CharField(max_length=64)),
                ('counterparty_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_entry_counterparties', to='locations.location')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='locations.location')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='stock_ledger.stocklot')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='stock_ledger.stockperiod')),
                ('reverses_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='stock_ledger.stockentry')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='product.unit')),
            ],
            options={
                'db_table': 'stock_entry',
                'indexes': [models.Index(fields=['lot', 'location', 'id'], name='idx_stock_entry_lot_loc'), models.Index(fields=['effective_at'], name='idx_stock_entry_effective'), models.Index(fields=['location', 'effective_at'], name='idx_stock_entry_location'), models.Index(fields=['source_document_type', 'source_document_id'], name='idx_stock_entry_document'), models.Index(fields=['transfer_group_id'], name='idx_stock_entry_transfer')],
            },
        ),
        migrations.AddConstraint(
            model_name='stockentry',
            constraint=models.UniqueConstraint(fields=('idempotency_key',), name='uq_stock_entry_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='stockentry',
            constraint=models.UniqueConstraint(fields=('entry_hash',), name='uq_stock_entry_hash'),
        ),
        migrations.AddConstraint(
            model_name='stockentry',
            constraint=models.CheckConstraint(check=models.Q(('entry_type__in', ['receipt', 'issue', 'transfer_out', 'transfer_in', 'production_output', 'production_consumption', 'count_adjustment', 'disposal', 'reversal'])), name='chk_stock_entry_type'),
        ),
        migrations.AddConstraint(
            model_name='stockentry',
            constraint=models.CheckConstraint(check=models.Q(('quantity', 0), _negated=True), name='chk_stock_entry_qty_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='stockentry',
            constraint=models.CheckConstraint(check=models.Q(('base_unit_factor__isnull', True), ('base_unit_factor__gt', Decimal('0')), _connector='OR'), name='chk_stock_entry_factor_pos'),
        ),
        migrations.AddConstraint(
            model_name='stockentry',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('base_unit_factor__isnull', True), ('quantity_base__isnull', True)), models.Q(('base_unit_factor__isnull', False), ('quantity_base__isnull', False)), _connector='OR'), name='chk_stock_entry_mass_pair'),
        ),
        migrations.AddConstraint(
            model_name='stockentry',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('authorised_by_user_id__isnull', True), ('override_reason__isnull', True)), models.Q(('authorised_by_user_id__isnull', False), ('override_reason__isnull', False)), _connector='OR'), name='chk_stock_entry_override'),
        ),
    ]
