# Generated by Django 4.2.30 on 2026-07-28 15:35

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productacceptance_productingredientlabel_and_more'),
        ('locations', '0002_loc_edge_relation_type'),
        ('stock_ledger', '0003_ledger_entry_chunk5'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockGenealogy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_base', models.DecimalField(decimal_places=6, max_digits=16)),
                ('input_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genealogy_as_input', to='stock_ledger.stockentry')),
                ('output_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genealogy_as_output', to='stock_ledger.stockentry')),
            ],
            options={
                'db_table': 'stock_genealogy',
            },
        ),
        migrations.CreateModel(
            name='StockChainAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_hash', models.CharField(max_length=64)),
                ('entry_count', models.BigIntegerField()),
                ('s3_object_key', models.CharField(max_length=255)),
                ('s3_version_id', models.CharField(blank=True, max_length=128, null=True)),
                ('anchored_at', models.DateTimeField()),
                ('head_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chain_anchors', to='stock_ledger.stockentry')),
            ],
            options={
                'db_table': 'stock_chain_anchor',
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=16)),
                ('quantity_base', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('updated_at', models.DateTimeField()),
                ('last_count_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stock_ledger.stockentry')),
                ('last_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stock_ledger.stockentry')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='locations.location')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='stock_ledger.stocklot')),
                ('negative_authorised_by_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stock_ledger.stockentry')),
            ],
            options={
                'db_table': 'stock_balance',
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('consumed', 'Consumed'), ('released', 'Released'), ('expired', 'Expired')], default='open', max_length=12)),
                ('source_document_type', models.CharField(blank=True, max_length=24, null=True)),
                ('source_document_id', models.BigIntegerField(blank=True, null=True)),
                ('source_document_line', models.IntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumed_by_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumed_reservations', to='stock_ledger.stockentry')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='locations.location')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='stock_ledger.stocklot')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='product.unit')),
            ],
            options={
                'db_table': 'stock_reservation',
                'indexes': [models.Index(fields=['lot', 'location', 'status'], name='idx_stock_reservation_open'), models.Index(fields=['source_document_type', 'source_document_id'], name='idx_stock_reservation_doc')],
            },
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['open', 'consumed', 'released', 'expired'])), name='chk_stock_reservation_status'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', Decimal('0'))), name='chk_stock_reservation_qty'),
        ),
        migrations.AddIndex(
            model_name='stockgenealogy',
            index=models.Index(fields=['input_entry'], name='idx_stock_genealogy_input'),
        ),
        migrations.AddConstraint(
            model_name='stockgenealogy',
            constraint=models.UniqueConstraint(fields=('output_entry', 'input_entry'), name='uq_stock_genealogy_edge'),
        ),
        migrations.AddConstraint(
            model_name='stockgenealogy',
            constraint=models.CheckConstraint(check=models.Q(('quantity_base__gt', Decimal('0'))), name='chk_stock_genealogy_qty'),
        ),
        migrations.AddIndex(
            model_name='stockchainanchor',
            index=models.Index(fields=['anchored_at'], name='idx_stock_chain_anchor_time'),
        ),
        migrations.AddConstraint(
            model_name='stockchainanchor',
            constraint=models.UniqueConstraint(fields=('head_entry',), name='uq_stock_chain_anchor_entry'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['location'], name='idx_stock_balance_location'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['last_entry'], name='idx_stock_balance_watermark'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('lot', 'location'), name='uq_stock_balance_lot_location'),
        ),
    ]
