# Generated by Django 4.2.30 on 2026-08-06 08:18

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_expand_category'),
        ('locations', '0002_loc_edge_relation_type'),
        ('stock_ledger', '0009_stock_entry_po_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_serial', models.CharField(max_length=32, unique=True)),
                ('quantity_initial', models.DecimalField(decimal_places=6, max_digits=16)),
                ('quantity_remaining', models.DecimalField(decimal_places=6, max_digits=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('partially_consumed', 'Partially consumed'), ('consumed', 'Consumed'), ('void', 'Void'), ('in_transit', 'In transit')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'stock_unit',
            },
        ),
        migrations.CreateModel(
            name='StockUnitConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_base', models.DecimalField(decimal_places=6, max_digits=16)),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_consumptions', to='stock_ledger.stockentry')),
                ('stock_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='stock_ledger.stockunit')),
            ],
            options={
                'db_table': 'stock_unit_consumption',
            },
        ),
        migrations.AddField(
            model_name='stockunit',
            name='created_by_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_units', to='stock_ledger.stockentry'),
        ),
        migrations.AddField(
            model_name='stockunit',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_units', to='locations.location'),
        ),
        migrations.AddField(
            model_name='stockunit',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='stock_ledger.stocklot'),
        ),
        migrations.AddField(
            model_name='stockunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_units', to='product.unit'),
        ),
        migrations.CreateModel(
            name='StockUnitPrintEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printed_at', models.DateTimeField()),
                ('actor_user_id', models.IntegerField(blank=True, null=True)),
                ('lan_username', models.CharField(blank=True, max_length=64, null=True)),
                ('source_workstation', models.CharField(blank=True, max_length=128, null=True)),
                ('reason', models.CharField(choices=[('initial', 'Initial'), ('reprint', 'Reprint'), ('relabel', 'Relabel')], max_length=16)),
                ('stock_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_events', to='stock_ledger.stockunit')),
            ],
            options={
                'db_table': 'stock_unit_print_event',
                'indexes': [models.Index(fields=['stock_unit', 'printed_at'], name='idx_stock_unit_print_unit')],
            },
        ),
        migrations.AddConstraint(
            model_name='stockunitprintevent',
            constraint=models.CheckConstraint(check=models.Q(('reason__in', ['initial', 'reprint', 'relabel'])), name='chk_stock_unit_print_reason'),
        ),
        migrations.AddConstraint(
            model_name='stockunitconsumption',
            constraint=models.UniqueConstraint(fields=('stock_unit', 'stock_entry'), name='uq_stock_unit_consumption'),
        ),
        migrations.AddConstraint(
            model_name='stockunitconsumption',
            constraint=models.CheckConstraint(check=models.Q(('quantity_base__gt', Decimal('0'))), name='chk_stock_unit_consumption_qty'),
        ),
        migrations.AddIndex(
            model_name='stockunit',
            index=models.Index(fields=['lot', 'location', 'status'], name='idx_stock_unit_lot_loc'),
        ),
        migrations.AddConstraint(
            model_name='stockunit',
            constraint=models.CheckConstraint(check=models.Q(('quantity_remaining__gte', Decimal('0')), ('quantity_remaining__lte', models.F('quantity_initial'))), name='chk_stock_unit_qty_bounds'),
        ),
        migrations.AddConstraint(
            model_name='stockunit',
            constraint=models.CheckConstraint(check=models.Q(('quantity_initial__gt', Decimal('0'))), name='chk_stock_unit_qty_initial'),
        ),
        migrations.AddConstraint(
            model_name='stockunit',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['active', 'partially_consumed', 'consumed', 'void', 'in_transit'])), name='chk_stock_unit_status'),
        ),
    ]
