# Generated by Django 4.2.30 on 2026-07-24 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('external_code', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('static', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('po_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loc_location',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocationStockProfile',
            fields=[
                ('location', models.OneToOneField(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stock_profile', serialize=False, to='locations.location')),
                ('stock_identifier', models.CharField(max_length=64)),
                ('production_identifier', models.CharField(max_length=64)),
                ('production_form_identifier', models.CharField(blank=True, max_length=64, null=True)),
                ('usage_form_identifier', models.CharField(blank=True, max_length=64, null=True)),
                ('real_stock', models.BooleanField(default=True)),
                ('min_shelf_life', models.IntegerField(blank=True, null=True)),
                ('max_shelf_life', models.IntegerField(blank=True, null=True)),
                ('use_by_modifier', models.IntegerField(blank=True, null=True)),
                ('extends_component_use_by', models.BooleanField(default=False)),
                ('metric_unit', models.IntegerField(blank=True, null=True)),
                ('document_header', models.CharField(blank=True, max_length=64, null=True)),
                ('default_report', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'loc_stock_profile',
            },
        ),
        migrations.CreateModel(
            name='LocationRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('internal', 'Internal'), ('process', 'Process'), ('supplier', 'Supplier'), ('customer', 'Customer'), ('courier', 'Courier'), ('depot', 'Depot'), ('storage', 'Storage'), ('transform', 'Transform')], max_length=32)),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='locations.location')),
            ],
            options={
                'db_table': 'loc_location_role',
            },
        ),
        migrations.CreateModel(
            name='LocationFeatureAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('customer_orders', 'Customer Orders'), ('customer_forecasts', 'Customer Forecasts'), ('production_plan_short', 'Production Plan Short'), ('picking_list', 'Picking List'), ('breakdown_list', 'Breakdown List'), ('linear_plan', 'Linear Plan'), ('issue_recipes', 'Issue Recipes'), ('staff_budget', 'Staff Budget'), ('anomaly_report_stk_in', 'Anomaly Report Stock In'), ('plan_closing_report', 'Plan Closing Report')], max_length=64)),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='locations.location')),
            ],
            options={
                'db_table': 'loc_location_feature',
            },
        ),
        migrations.CreateModel(
            name='LocationEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(db_column='child_id', on_delete=django.db.models.deletion.CASCADE, related_name='parent_edges', to='locations.location')),
                ('parent', models.ForeignKey(db_column='parent_id', on_delete=django.db.models.deletion.CASCADE, related_name='child_edges', to='locations.location')),
            ],
            options={
                'db_table': 'loc_location_edge',
            },
        ),
        migrations.CreateModel(
            name='LocationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('contact_type', models.IntegerField(blank=True, null=True)),
                ('contact_value', models.CharField(blank=True, max_length=64, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='locations.location')),
            ],
            options={
                'db_table': 'loc_contact',
            },
        ),
        migrations.CreateModel(
            name='LocationAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('contact_point_name', models.CharField(blank=True, max_length=64, null=True)),
                ('contact_point_phone', models.CharField(blank=True, max_length=16, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='locations.location')),
            ],
            options={
                'db_table': 'loc_address',
            },
        ),
        migrations.AddConstraint(
            model_name='locationroleassignment',
            constraint=models.UniqueConstraint(fields=('location', 'role'), name='uq_loc_location_role'),
        ),
        migrations.AddConstraint(
            model_name='locationfeatureassignment',
            constraint=models.UniqueConstraint(fields=('location', 'feature'), name='uq_loc_location_feature'),
        ),
        migrations.AddConstraint(
            model_name='locationedge',
            constraint=models.UniqueConstraint(fields=('parent', 'child'), name='uq_loc_location_edge'),
        ),
        migrations.AddConstraint(
            model_name='locationedge',
            constraint=models.CheckConstraint(check=models.Q(('parent', models.F('child')), _negated=True), name='chk_loc_edge_parent_ne_child'),
        ),
    ]
