# Generated by Django 4.2.30 on 2026-07-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_loc_schema_chunk1'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='locationedge',
            name='uq_loc_location_edge',
        ),
        migrations.AddField(
            model_name='locationedge',
            name='relation_type',
            field=models.CharField(choices=[('zone_group', 'Zone group'), ('subordinate_storage', 'Subordinate storage')], default='zone_group', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='locationedge',
            constraint=models.UniqueConstraint(fields=('relation_type', 'parent', 'child'), name='uq_loc_location_edge'),
        ),
        migrations.AddConstraint(
            model_name='locationedge',
            constraint=models.UniqueConstraint(fields=('relation_type', 'child'), name='uq_loc_location_edge_child_per_type'),
        ),
    ]
