# Generated by Django 4.2.30 on 2026-08-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_loc_edge_relation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationstockprofile',
            name='show_incomplete_stock',
            field=models.BooleanField(default=False),
        ),
    ]
