# Generated by Django 4.2.30 on 2026-08-10 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_show_incomplete_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSupplierProfile',
            fields=[
                ('location', models.OneToOneField(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='supplier_profile', serialize=False, to='locations.location')),
                ('approval_status', models.CharField(blank=True, choices=[('approved', 'Approved'), ('pending', 'Pending'), ('suspended', 'Suspended')], max_length=16, null=True)),
                ('approval_expires_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loc_supplier_profile',
            },
        ),
        migrations.AddField(
            model_name='locationstockprofile',
            name='is_quarantine',
            field=models.BooleanField(default=False),
        ),
    ]
